title: Möbelmanufaktur Menke
author: Lars Menke
email: info@moebelmanufaktur-menke.com
description: >-
  Möbelmanufaktur Menke, wir stehen für

social:
  twitter: 
  facebook: 
  instagram: MoebelmanufakturMenke
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
