title: Möbelmanufaktur Menke
author: Lars Menke
email: info@moebelmanufaktur-menke.com
description: >-
  Möbelmanufaktur Menke, wir stehen für
  <ul>
    <li>Innovation u. Kreativität</li>
    <li>Individualität</li>
    <li>Flexibilität</li>
  </ul>

social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
