title: Möbelmanufaktur Menke
author: Lars Menke
email: info@moebelmanufaktur-menke.com
description: >-
  Möbelmanufaktur Menke, wir stehen für
d1: - Innovation u. Kreativität
d2: - Individualität
d3: - Flexibilität


social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
