title: Multiverse by HTML5 UP
author: Lars Menke
  email: l.mm@aol.com
description: >-
  Moebelmanufaktur Menke, die Tischlerei Ihres Vertrauens

social:
  twitter: LMenke
  facebook: LMenke
  instagram: LMenke
  github: LMenke
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
